[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
    [main.params]
        icon = "archives"

[[main]]
    identifier = "topics"
    name = "专题"
    url = "/tags/专题指南/"
    weight = 3
    [main.params]
        icon = "categories"

[[main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 4
    [main.params]
        icon = "tag"

[[main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 5
    [main.params]
        icon = "search"

[[main]]
    identifier = "projects"
    name = "项目"
    url = "/projects/"
    weight = 6
    [main.params]
        icon = "folder"

[[main]]
    identifier = "about"
    name = "我的"
    url = "/about/"
    weight = 7
    [main.params]
        icon = "user"

[[main]]
    identifier = "links"
    name = "友链"
    url = "/links/"
    weight = 8
    [main.params]
        icon = "link"

[[main]]
    identifier = "guestbook"
    name = "留言板"
    url = "/guestbook/"
    weight = 9
    [main.params]
        icon = "messages"
